name: Gradle CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}
      - run: ./gradlew build
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-test-report
          path: '**/build/reports/tests/test'
